version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: social-postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_SSL: "on"
      POSTGRES_SSL_CERT_FILE: "/etc/postgresql/server.crt"
      POSTGRES_SSL_KEY_FILE: "/etc/postgresql/server.key"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres-certs:/etc/postgresql
    command: postgres -c ssl=on -c ssl_cert_file=/etc/postgresql/server.crt -c ssl_key_file=/etc/postgresql/server.key

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    container_name: social-redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

volumes:
  db-data:
