name: Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Install dependencies
        run: go mod tidy

      - name: Run audit
        run: go run cmd/api/main.go audit
      
      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Run lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run

      - name: Run staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...

      # - name: Run security audit
      #   run: go run github.com/securego/gosec/v2/cmd/gosec@latest ./...